"""empty message

Revision ID: 831e511806a6
Revises: b66459bc8ab3
Create Date: 2021-11-15 17:15:23.335840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831e511806a6'
down_revision = 'b66459bc8ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_add_time'), 'todo', ['add_time'], unique=False)
    op.create_index(op.f('ix_user_add_time'), 'user', ['add_time'], unique=False)
    op.create_unique_constraint(None, 'user', ['name'])
    op.create_unique_constraint(None, 'user', ['face'])
    op.create_unique_constraint(None, 'user', ['sex'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_add_time'), table_name='user')
    op.drop_index(op.f('ix_todo_add_time'), table_name='todo')
    op.drop_table('todo')
    # ### end Alembic commands ###
